# Generated by Django 4.0.5 on 2022-07-11 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrldbldr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('file', models.ImageField(upload_to='avatars/')),
                ('race', models.CharField(default='', max_length=200)),
                ('sex', models.CharField(default='f', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('file', models.ImageField(upload_to='backgrounds/')),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=200, primary_key=True, serialize=False, unique=True)),
                ('file', models.ImageField(upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Location_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='No Name Given', max_length=200, unique=True)),
                ('alternate_names', models.TextField(blank=True, default='')),
                ('is_shop', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200, unique=True)),
                ('color', models.CharField(default='#000000', max_length=12)),
                ('threshold', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='copper',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='fiscal_status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='map_location_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='silver',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settlement',
            name='clone_of',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wrldbldr.settlement'),
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200, unique=True)),
                ('has_expertise', models.BooleanField(default=False)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('location_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='wrldbldr.location_type')),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('name', models.CharField(default='No Name Given', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('occupation', models.CharField(blank=True, default='', max_length=120)),
                ('personality', models.CharField(blank=True, default='', max_length=120)),
                ('race', models.CharField(blank=True, default='', max_length=120)),
                ('spec', models.CharField(blank=True, default='', max_length=120)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('avatar', models.TextField(blank=True, default='')),
                ('traits', models.TextField(blank=True, default='')),
                ('location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='wrldbldr.location')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('name', models.CharField(default='No Name Given', max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('quantity_low', models.IntegerField(default=1)),
                ('quantity_high', models.IntegerField(default=10)),
                ('gold', models.IntegerField(default=0)),
                ('silver', models.IntegerField(default=0)),
                ('copper', models.IntegerField(default=0)),
                ('vary_cost', models.BooleanField(default=False)),
                ('is_service', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='wrldbldr.location')),
                ('location_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='wrldbldr.location_type')),
                ('rarity', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='wrldbldr.rarity')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='wrldbldr.location_type'),
        ),
    ]
