# Generated by Django 4.1 on 2022-09-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrldbldr', '0002_avatar_background_icon_location_type_rarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='thumbnail',
            field=models.ImageField(default=None, null=True, upload_to='avatars/'),
        ),
    ]
