# Generated by Django 4.0.8 on 2022-12-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrldbldr', '0004_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='No Name Given', max_length=200),
        ),
    ]
